# Generated by Django 4.1.7 on 2023-04-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255)),
                ('time', models.TimeField(max_length=255)),
                ('task', models.CharField(choices=[('GI', 'General inqury'), ('SS', 'support and speed issues'), ('P', 'Provision'), ('S', 'Site down fiber loss or power loss')], max_length=255)),
                ('details', models.TextField(max_length=400)),
            ],
        ),
    ]
