# Generated by Django 4.1.7 on 2023-04-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_input',
        ),
    ]
