# Generated by Django 4.1.7 on 2023-04-30 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_delete_user_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255)),
                ('time', models.TimeField(max_length=255)),
                ('task', models.CharField(choices=[('GI', 'General inqury'), ('SS', 'support and speed issues'), ('P', 'Provision'), ('S', 'Site down fiber loss or power loss')], max_length=255)),
                ('details', models.TextField(max_length=400)),
                ('images', models.ImageField(blank=True, null=True, upload_to='acceptanceSheet/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
